// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Task struct {
	ID        uuid.UUID             `json:"id"`
	TaskType  string                `json:"task_type"`
	Payload   pqtype.NullRawMessage `json:"payload"`
	Status    string                `json:"status"`
	RunAt     time.Time             `json:"run_at"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
}
