// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks(id, task_type, payload, status,  run_at, created_at, updated_at)
VALUES( 
  gen_random_uuid(),
  $1,
  $2,
  $3,
  $4,
  NOW(),
  NOW()
)
RETURNING id, task_type, payload, status, run_at, created_at, updated_at
`

type CreateTaskParams struct {
	TaskType string    `json:"task_type"`
	Payload  []byte    `json:"payload"`
	Status   string    `json:"status"`
	RunAt    time.Time `json:"run_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TaskType,
		arg.Payload,
		arg.Status,
		arg.RunAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Payload,
		&i.Status,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingTasksForUpdate = `-- name: GetPendingTasksForUpdate :many
SELECT id, task_type, payload, status, run_at, created_at, updated_at FROM tasks
WHERE status = 'PENDING' 
  AND run_at <= NOW()
ORDER BY run_at ASC
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingTasksForUpdate(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getPendingTasksForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Payload,
			&i.Status,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStalledTasks = `-- name: GetStalledTasks :many
SELECT id, task_type, payload, status, run_at, created_at, updated_at FROM tasks
WHERE status IN ('RUNNING', 'QUEUED')
AND updated_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) GetStalledTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getStalledTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Payload,
			&i.Status,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, task_type, payload, status, run_at, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Payload,
		&i.Status,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByStatus = `-- name: GetTasksByStatus :many
SELECT id, task_type, payload, status, run_at, created_at, updated_at FROM tasks
WHERE status = $1 
ORDER BY run_at DESC
`

func (q *Queries) GetTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Payload,
			&i.Status,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateTaskStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
