// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/grpcapi/services.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_PENDING  TaskStatus = 0
	TaskStatus_QUEUED   TaskStatus = 1
	TaskStatus_RUNNING  TaskStatus = 2
	TaskStatus_COMPLETE TaskStatus = 3
	TaskStatus_FAILED   TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "PENDING",
		1: "QUEUED",
		2: "RUNNING",
		3: "COMPLETE",
		4: "FAILED",
	}
	TaskStatus_value = map[string]int32{
		"PENDING":  0,
		"QUEUED":   1,
		"RUNNING":  2,
		"COMPLETE": 3,
		"FAILED":   4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpcapi_services_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_internal_grpcapi_services_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpcapi_services_proto_rawDescGZIP(), []int{0}
}

type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_internal_grpcapi_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcapi_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_internal_grpcapi_services_proto_rawDescGZIP(), []int{0}
}

func (x *MessageAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_internal_grpcapi_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcapi_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcapi_services_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuUsage       float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                  // Current CPU %
	AvailableSlots int32                  `protobuf:"varint,3,opt,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"` // How many more tasks can I handle?
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_grpcapi_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcapi_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcapi_services_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableSlots() int32 {
	if x != nil {
		return x.AvailableSlots
	}
	return 0
}

type UpdateTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=grpcapi.TaskStatus" json:"status,omitempty"`
	LogMessage    string                 `protobuf:"bytes,3,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"` // for logging task status in scheduler
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusRequest) Reset() {
	*x = UpdateTaskStatusRequest{}
	mi := &file_internal_grpcapi_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusRequest) ProtoMessage() {}

func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcapi_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcapi_services_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_PENDING
}

func (x *UpdateTaskStatusRequest) GetLogMessage() string {
	if x != nil {
		return x.LogMessage
	}
	return ""
}

var File_internal_grpcapi_services_proto protoreflect.FileDescriptor

const file_internal_grpcapi_services_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/grpcapi/services.proto\x12\agrpcapi\"&\n" +
	"\n" +
	"MessageAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"@\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"u\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12'\n" +
	"\x0favailable_slots\x18\x03 \x01(\x05R\x0eavailableSlots\"\x80\x01\n" +
	"\x17UpdateTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.grpcapi.TaskStatusR\x06status\x12\x1f\n" +
	"\vlog_message\x18\x03 \x01(\tR\n" +
	"logMessage*L\n" +
	"\n" +
	"TaskStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042H\n" +
	"\rWorkerService\x127\n" +
	"\n" +
	"SubmitTask\x12\x14.grpcapi.TaskRequest\x1a\x13.grpcapi.MessageAck2\x98\x01\n" +
	"\tScheduler\x12@\n" +
	"\x0eSendHearthbeat\x12\x19.grpcapi.HeartbeatRequest\x1a\x13.grpcapi.MessageAck\x12I\n" +
	"\x10UpdateTaskStatus\x12 .grpcapi.UpdateTaskStatusRequest\x1a\x13.grpcapi.MessageAckB<Z:github.com/Mohd-Sayeedul-Hoda/task_runner/internal/grpcapib\x06proto3"

var (
	file_internal_grpcapi_services_proto_rawDescOnce sync.Once
	file_internal_grpcapi_services_proto_rawDescData []byte
)

func file_internal_grpcapi_services_proto_rawDescGZIP() []byte {
	file_internal_grpcapi_services_proto_rawDescOnce.Do(func() {
		file_internal_grpcapi_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpcapi_services_proto_rawDesc), len(file_internal_grpcapi_services_proto_rawDesc)))
	})
	return file_internal_grpcapi_services_proto_rawDescData
}

var file_internal_grpcapi_services_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpcapi_services_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpcapi_services_proto_goTypes = []any{
	(TaskStatus)(0),                 // 0: grpcapi.TaskStatus
	(*MessageAck)(nil),              // 1: grpcapi.MessageAck
	(*TaskRequest)(nil),             // 2: grpcapi.TaskRequest
	(*HeartbeatRequest)(nil),        // 3: grpcapi.HeartbeatRequest
	(*UpdateTaskStatusRequest)(nil), // 4: grpcapi.UpdateTaskStatusRequest
}
var file_internal_grpcapi_services_proto_depIdxs = []int32{
	0, // 0: grpcapi.UpdateTaskStatusRequest.status:type_name -> grpcapi.TaskStatus
	2, // 1: grpcapi.WorkerService.SubmitTask:input_type -> grpcapi.TaskRequest
	3, // 2: grpcapi.Scheduler.SendHearthbeat:input_type -> grpcapi.HeartbeatRequest
	4, // 3: grpcapi.Scheduler.UpdateTaskStatus:input_type -> grpcapi.UpdateTaskStatusRequest
	1, // 4: grpcapi.WorkerService.SubmitTask:output_type -> grpcapi.MessageAck
	1, // 5: grpcapi.Scheduler.SendHearthbeat:output_type -> grpcapi.MessageAck
	1, // 6: grpcapi.Scheduler.UpdateTaskStatus:output_type -> grpcapi.MessageAck
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_grpcapi_services_proto_init() }
func file_internal_grpcapi_services_proto_init() {
	if File_internal_grpcapi_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpcapi_services_proto_rawDesc), len(file_internal_grpcapi_services_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_grpcapi_services_proto_goTypes,
		DependencyIndexes: file_internal_grpcapi_services_proto_depIdxs,
		EnumInfos:         file_internal_grpcapi_services_proto_enumTypes,
		MessageInfos:      file_internal_grpcapi_services_proto_msgTypes,
	}.Build()
	File_internal_grpcapi_services_proto = out.File
	file_internal_grpcapi_services_proto_goTypes = nil
	file_internal_grpcapi_services_proto_depIdxs = nil
}
